AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a cross account role to give an account access to an ECR repository in current account
Parameters:
  AccountId:
    Description: AWS Account ID which is allowed to assume this role
    Type: String
Resources:
  ECRCrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            AWS: !Sub 'arn:aws:iam::${AccountId}:root'
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: ECRPushAccess
        PolicyDocument:
          Statement:
          - Sid: Stmt1452746887373
            Effect: Allow
            Action:
            - ecr:*
            Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*'
          - Sid: Stmt1452746887373
            Effect: Deny
            Action:
            - ecr:BatchDeleteImage
            - ecr:DeleteRepositoryPolicy
            - ecr:SetRepositoryPolicy
            Resource: !Sub 'arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/*'            
          - Sid: Stmt1452746887374
            Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            Resource: '*'                    
Outputs:
  RoleArn:
    Description: The ARN of the cross account role
    Value: !GetAtt ECRCrossAccountRole.Arn