AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Creates roles for jenkins slave tasks. This is meant to be used when ECR resides in the same account as Jenkins
Parameters:
  ECRRepoArn:
    Description: The ECR ARN if ECR resides in the same account as Jenkins (and not in another account)
    Type: String
  JenkinsCacheBucket:
    Description: The name of the jenkins cache bucket
    Type: String
Resources:
  JenkinsSlaveRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: JenkinsSlaveRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: ''
          Effect: Allow
          Principal:
            Service: ecs-tasks.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: JenkinsSlaveECRLocalPolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
              - ecr:*
            Resource: !Ref 'ECRRepoArn'
          - Effect: Deny
            Action:
              - ecr:BatchDeleteImage
              - ecr:DeleteRepositoryPolicy
              - ecr:SetRepositoryPolicy
            Resource: !Ref 'ECRRepoArn'
      - PolicyName: JenkinsSlaveS3Cache
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${JenkinsCacheBucket}/*'
          - Effect: Allow
            Action:
            - s3:ListBucket
            Resource: !Sub 'arn:aws:s3:::${JenkinsCacheBucket}'

Outputs:
  TaskRoleArn:
    Description: The ARN of the jenkins slave role
    Value: !GetAtt JenkinsSlaveRole.Arn